lang: cs-CZ
title: Návody
author:
  name: Tomáš Matějíček
  email: t@te23.cz

description: >
  Postupy a návody

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

remote_theme: jekyll/minima

sass:
  style: compressed

baseurl: /

minima:
  date_format: "%Y-%m-%d"
