lang: cs-CZ
title: Návody
author:
  name: Tomáš Matějíček
  email: t@te23.cz

description: >
  Postupy a návody

plugins:
  - jekyll-remote-theme

remote_theme: jekyll/minima

baseurl: /

minima:
  show_excerpts: true
  date_format: "%Y-%m-%d"
